version: 3

pullapprove_conditions:
- condition: "base.ref == 'master'"
  unmet_status: success
  explanation: "Review not required unless merging to master"
- condition: "base.ref == 'ra_master_pullapprove_yml'"
  unmet_status: success
  explanation: "Review not required unless merging to master"
- condition: "'*travis*' in statuses.successful"
  unmet_status: failure
  explanation: "Tests must pass before review starts"

notifications:
- when: pull_request.opened
  # only need to send this to external-contributors
  if: "author_association in ['FIRST_TIMER', 'FIRST_TIME_CONTRIBUTOR', 'CONTRIBUTOR']"
  comment: >
    Hey @{{ author }}, please make sure your tests pass and you have looked everything over. Then we will review.

    Thanks for the PR!
- when: pullapprove.approved
  comment: "The review is completed. @exampleuser, please merge this in when ready."

groups:
  pullapprove-admins:  # group name
    conditions:  # the group is activated when all of these statements are true
      - "'*.py' in files"
    reviewers:  # people who can approve for this group
      users:
        - rhiananthony
      teams:
        - pipelines-team
    reviews:  # settings for approval and reviewer selection
        required: 1  # 1 approval1 from this group are required
        request: 1  # 1 review request will be sent at a time
        request_order: given  # reviewers will be selected in the given order
        author_value: 1  # if the PR author is in this group, automatically add +1
        
